name: Test Validation

on:
  push:
    branches:
      - main

jobs:
  validate_1:
    runs-on: ubuntu-latest
    steps:
      - name: check environment variable
        if: ${{
          github
            .event
            .pull_request
            .head
            .ref
        }}
        run: echo "env.1abc is invalid"
        continue-on-error: true
