name: Test Validation

on:
  push:
    branches:
      - main

env:
  startsWith: "my value"
  # 1: "a"
  # null: a
  true: b
  # undefined: b

jobs:
  "a":
    runs-on: ubuntu-latest
    steps:
      - name: check environment variable
        if: ${{true}}
        run: echo "env.1abc is invalid"
        continue-on-error: true
