name: Test Validation

on:
  push:
    branches:
      - main

env:
  startsWith: "my value"

jobs:
  validate_1:
    runs-on: ubuntu-latest
    steps:
      - name: check environment variable
        if: ${{ fromJSON('{ "path": "C:\\\\Users\\\\user" }').path }}

        run: echo "env.1abc is invalid"
        continue-on-error: true
