name: Test Validation

on:
  push:
    branches:
      - main

env:
  startsWith: "my value"
  # 1: "a"
  # null: a
  true: "We can read this."
  # undefined: b

jobs:
  "a":
    runs-on: ubuntu-latest
    steps:
      - name: check environment variable
        run: echo ${{ env.true}}
        continue-on-error: true
