name: Test Validation

on:
  push:
    branches:
      - main

jobs:
  validate_1:
    runs-on: ubuntu-latest
    steps:
      - name: valid nested index access
        if: ${{'aaaa'}}${{'aaaa'}} == 'aaaaaaaa'
        run: echo "nested index works"
        continue-on-error: true
