name: Test Validation

on:
  push:
    branches:
      - main

env:
  # 1: "a"
  # null: a
  true: "We can read this true"
  false: "We can read this false"
  undefined: "We can read this undefined"

jobs:
  "a":
    runs-on: ubuntu-latest
    steps:
      - name: check environment variable
        run: |
          echo ${{ env.true}}
          echo ${{ env.false}}
          echo ${{ env.undefined}}
        continue-on-error: true
