name: Test Validation

on:
  push:
    branches:
      - main

env:
  1abc: "invalid"

jobs:
  validate_1:
    runs-on: ubuntu-latest
    steps:
      - name: valid nested index access
        if: ${{'aaaa'}}${{'aaaa'}} == 'aaaaaaaa'
        run: echo "nested index works"
        continue-on-error: true

      - name: check environment variable
        if: env.1abc == 'invalid'
        run: echo "env.1abc is invalid"
        continue-on-error: true
